### ISSUE TITLE
FASTComment has been removed

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/FAST#13]
In _v2_, FASTComment has been removed, but FASTTComment has not been created.
Since it can be used in language specific AST, and in UI, I would love you to reintroduce the FASTTComment concept

**Comment by enwiro** [comment]
Fix with commit https://github.com/moosetechnology/FAST/commit/61b2cea0f5424b0f3484baead7b8366d36f795b5
I use the same implementation than in Famix.
