### ISSUE TITLE
Remove empty GTExtensions package

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/FAST#14]
The `FAST-GTExtensions` package has been empty since [this commit](https://github.com/moosetechnology/FAST/commit/0563f15cf8a4a02540e34e122b88695b80fc7e13) almost 2 years ago.
Here's what it used to contain: https://github.com/moosetechnology/FAST/blob/f6823f3a2b72715f7842d0c3457f9ed2dd4c1513/src/FAST-GTExtensions/FASTEntity.extension.st
Perhaps the deletion was unintentional, but since no other changes or issues have been made, it may be time to remove the package.

**Comment by badetitou** [comment]
Yes, we can remove it
