### ISSUE TITLE
FAST-Core-Visitor -> defaultOperatorsPrecedence misses the unary '!' operator for Java

### ISSUE THREAD

**Issue by RomainDeg** [moosetechnology/FAST#47]
How to reproduce bug (in a playground, with FAST-Java library) :

```st
methodCode := 'public test() {
	boolean toto = !true;
}'.

fastMethod := (JavaSmaCCProgramNodeImporterVisitor new 
      parseCodeMethodString: methodCode) allFASTNamedBehaviouralEntity first.

FASTJavaExportVisitor new export: fastMethod
``` 

In the dictionary in `FASTTExporter>>defaultOperatorsPrecedence`, unary operators have the prefix or postfix "unary", but the '!' operator does not have that postfix.

Adding the key / value `#'!unary' -> 110.` fixes the issue, but I'm opening the issue as I am unsure whether the value 110 is correct, or if this key / value should entirely replace the original  `#'!' -> 110.` (Other languages might use that as an different operator? Seems unlikely though.)

**Comment by NicolasAnquetil** [comment]
Well spotted.
So short answer is: yes #'!unary' should be introduced in the dictionary with the precedence value 110 (the one of '!')

- Can you submit your fix (PR) ?
- Don't forget to create a test
- I see that `FASTJavaExportVisitor` still has a method #initialize on class side. This is a remnant of the first implementation. Could you remove it while you are on this ?
